name: Publish to NPM

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          # version: 11
          run_install: false
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Publish package
        # Currently, only npm supports publishing packages with provenance
        # https://docs.npmjs.com/generating-provenance-statements
        # npm install --force
        # npm publish --provenance --access public
        run: |
          pnpm install --frozen-lockfile
          pnpm --filter ./packages/markdown-it-steps test
          pnpm --filter ./packages/markdown-it-steps build
          pnpm publish --filter ./packages/markdown-it-steps --no-git-checks
